# -*- coding: utf-8 -*-
"""Kings House.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fntvfMtRwAFYU0X3vGgJiu5sNgeBwBS9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

king=pd.read_csv('/content/2025_Python1_King_house.csv')

king_zip = pd.read_csv('/content/2025_Python3_King_zip.csv')

merged_df=pd.merge(king,king_zip,on=['id','date'],how='left')

merged_df.id.value_counts()

merged_df.sort_values(by=['id','date'],inplace=True)
merged_df.drop_duplicates(subset=['id'],keep='last',inplace=True)
merged_df['m_price']=merged_df['price']/1000000
merged_df['age']=2025-merged_df['yr_built']
merged_df.loc[merged_df.yr_renovated!=0,'age']=2025-merged_df.yr_renovated
merged_df['date']=pd.to_datetime(merged_df.date.str[:8],format='%Y%m%d')

merged_df.info()

!pip -q install plotly.express

import plotly.express as px
fig=px.scatter_mapbox(merged_df,lat='lat',lon='long',color='m_price',size='m_price',zoom=9,height=680,width=980)
fig.update_layout(mapbox_style='open-street-map')
fig.show()

import plotly.express as px
fig=px.scatter_mapbox(merged_df,lat='lat',lon='long',color='m_price',size='age',zoom=9,height=680,width=980)
fig.update_layout(mapbox_style='open-street-map')
fig.show()

import statsmodels.formula.api as smf
reg1='''m_price~bedrooms+bathrooms+sqft_living+sqft_above+sqft_basement+sqft_lot+floors+waterfront+condition+age'''
reg1_output=smf.ols(reg1,data=merged_df).fit()
print(reg1_output.summary())

reg2='''m_price~bedrooms+bathrooms+sqft_living+sqft_above+sqft_basement+sqft_lot+floors+waterfront+condition+age+C(zipcode)'''
reg2_output=smf.ols(reg2,data=merged_df).fit()
print(reg2_output.summary())

merged_df['fitted_value1']=reg2_output.fittedvalues.copy()
merged_df['residuals1']=merged_df.m_price-merged_df.fitted_value1
import seaborn as sns
sns.scatterplot(data=merged_df,x='fitted_value1',y='residuals1')

merged_df['fitted_value1']=reg1_output.fittedvalues.copy()
merged_df['residuals1']=merged_df.m_price-merged_df.fitted_value1
import seaborn as sns
sns.scatterplot(data=merged_df,x='fitted_value1',y='residuals1')

import matplotlib.pyplot as plt
fig,axs=plt.subplots(nrows=2,ncols=1,figsize=(10,12))

# Recalculate fitted_value1 and residuals1 to ensure consistency for plotting axs[0]
merged_df['fitted_value1']=reg1_output.fittedvalues.copy()
merged_df['residuals1']=merged_df.m_price-merged_df.fitted_value1

# Create fitted_value2 and residuals2 using reg2_output
merged_df['fitted_value2']=reg2_output.fittedvalues.copy()
merged_df['residuals2']=merged_df.m_price-merged_df.fitted_value2

sns.scatterplot(data=merged_df,x='fitted_value1',y='residuals1',ax=axs[0])
sns.scatterplot(data=merged_df,x='fitted_value2',y='residuals2',ax=axs[1])

features=['bedrooms','bathrooms','sqft_living','sqft_above','sqft_basement','sqft_lot','floors','waterfront','condition','age']
#how do we calculate correlation (correlation map)

sns.heatmap(merged_df[features].corr(),annot=True)
#aldingining aqirina qoyip koriw kerek